
# intact
INTACT_VERSION = '2026-01-09'

# cluster
IEVALUE_THRESHOLD = 1e-5
OVERLAP_THRESHOLD = 0.75
FAMILIES = [
    'HSP70, MreB_Mbl',
    'PK_Tyr_Ser-Thr, Pkinase',
    'Arf, Roc, Ras',
    '7tm_1',
]
NEGATIVE_TO_POSITIVE_RATIO = 10

# learn
SEED = 42
TRAIN_FRACTION = 0.75
VAL_FRACTION = 0
TEST_FRACTION = 0.25
ESM2_MODEL = '8M'
BATCH_SIZE = 64
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0
PATIENCE = 4
MIN_DELTA = 1e-4
REPETITIONS = 10
EPOCHS = 20

# models
CLASSIFICATION_HEAD_HIDDEN_DIMS = [64, 64]
CLASSIFICATION_HEAD_DROPOUT = 0.3
