"""
===============================================================================
Title:      Domtblout
Outline:    Domtblout class to parse the .domtblout file generated by hmmscan, 
            and return a pandas DataFrame (filtered on e-values). Also, 
            aggregates the Pfam domains of each query sequence dealing with
            overlapping domains to obtain the domain architecture.
Docs:       http://eddylab.org/software/hmmer/Userguide.pdf
Author:     Alejandro Sánchez Cano
Date:       04/09/2026
===============================================================================
"""

# Built-in modules
from typing import Literal

# Third-party modules
import numpy as np
import pandas as pd

# Custom modules
from domain_architecture import DomainArchitecture

class Domtblout:

    @classmethod
    def from_df(cls, df: pd.DataFrame) -> 'Domtblout':
        '''
        Create a Domtblout instance from an existing DataFrame.

        Parameters
        ----------
        df : pd.DataFrame
            A pandas DataFrame containing the parsed data from a .domtblout 
            file.

        Returns
        -------
        Domtblout
            An instance of the Domtblout class initialized with the provided 
            DataFrame.
        '''
        instance = cls.__new__(cls)
        instance.df = df
        return instance

    @classmethod
    def from_file(cls, file_path: str) -> 'Domtblout':
        '''
        Create a Domtblout instance from a .domtblout file.

        Parameters
        ----------
        file_path : str
            The path to the .domtblout file generated by hmmscan.

        Returns
        -------
        Domtblout
            An instance of the Domtblout class initialized with the parsed 
            DataFrame from the specified file.
        '''
        instance = cls.__new__(cls)
        instance.file_path = file_path
        instance.df = instance.__parse()
        return instance

    @classmethod
    def from_df_file(cls, file_path: str) -> 'Domtblout':
        '''
        Create a Domtblout instance from a .domtblout file and return the 
        corresponding DataFrame.

        Parameters
        ----------
        file_path : str
            The path to the .domtblout file generated by hmmscan.

        Returns
        -------
        Domtblout
            An instance of the Domtblout class initialized with the parsed 
            DataFrame from the specified file.
        '''
        instance = cls.__new__(cls)
        instance.file_path = file_path
        instance.df = pd.read_csv(file_path, sep='\t')
        return instance

    def __parse(self) -> pd.DataFrame:
        '''
        Parse the .domtblout file generated by hmmscan and return a pandas 
        DataFrame with the relevant columns.

        Returns
        -------
        pd.DataFrame
            DataFrame containing the parsed data from the .domtblout file.
        '''
        # Define columns
        columns = [
            'target_name', 'pfam_accession', 'target_length',
            'query_name', 'query_accession', 'query_length',
            'evalue', 'full_score', 'full_bias',
            'domain_num', 'domain_of', 'c_evalue', 'i_evalue', 'domain_score', 'domain_bias',
            'hmm_from', 'hmm_to', 'ali_from', 'ali_to', 'env_from', 'env_to', 
            'acc', 'description'
        ]

        # Build dataframe
        rows = []
        with open(self.file_path) as f:
            for line in f:
                
                # Skip HMMER comments and blank lines
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                
                # Split line into 23 fields, keeping the description together
                fields = line.split(maxsplit=22)
                if len(fields) != len(columns):
                    raise ValueError(f"Expected {len(columns)} fields, got {len(fields)}: {line}")

                # Append fields to rows
                rows.append(fields)

        # Create dataframe
        self.df = pd.DataFrame(rows, columns=columns)
        self.df['target_length'] = self.df['target_length'].astype(int)
        self.df['query_length'] = self.df['query_length'].astype(int)
        self.df['evalue'] = self.df['evalue'].astype(float)
        self.df['full_score'] = self.df['full_score'].astype(float)
        self.df['full_bias'] = self.df['full_bias'].astype(float)
        self.df['i_evalue'] = self.df['i_evalue'].astype(float)
        self.df['c_evalue'] = self.df['c_evalue'].astype(float)
        self.df['domain_score'] = self.df['domain_score'].astype(float)
        self.df['domain_bias'] = self.df['domain_bias'].astype(float)
        self.df['hmm_from'] = self.df['hmm_from'].astype(int)
        self.df['hmm_to'] = self.df['hmm_to'].astype(int)
        self.df['ali_from'] = self.df['ali_from'].astype(int)
        self.df['ali_to'] = self.df['ali_to'].astype(int)
        self.df['env_from'] = self.df['env_from'].astype(int)
        self.df['env_to'] = self.df['env_to'].astype(int)
        self.df['acc'] = self.df['acc'].astype(float)
        return self.df

    def evalue_filter(
        self, 
        field: str, 
        threshold: float
    ) -> pd.DataFrame:
        '''
        Filter the DataFrame based on a specified e-value threshold.

        Parameters
        ----------
        field : str
            The column name to filter on (e.g., 'c_evalue', 'i_evalue').

        threshold : float
            The e-value threshold for filtering.
        
        Returns
        -------
        pd.DataFrame
            A filtered DataFrame containing only rows where the specified field's
            value is less than the given threshold.
        '''
        self.df = self.df[self.df[field] < threshold]
        return self.df

    def solve_overlap(
        self, 
        alignment: Literal['ali', 'env'] = 'env',
        threshold: float = 0.5
    ) -> tuple[dict[str, DomainArchitecture], np.ndarray]:
        '''
        Solve overlapping Pfam domains for each query sequence based on the 
        specified alignment type and overlap threshold.

        Parameters
        ----------
        alignment : str, optional
            The type of alignment to consider for overlap ('ali' or 'env'), by 
            default 'env'.
        
        threshold : float, optional
            The overlap threshold to determine if two domains are considered 
            overlapping, by default 0.5.

        Returns
        -------
        dict[str, DomainArchitecture]
            A dictionary mapping each query sequence name to a 
            DomainArchitecture object representing the architecture of 
            overlapping Pfam domains.

        np.ndarray
            An array containing the overlap ratios for each pair of overlapping
            domains.
        '''
        # Sort dataframe
        df = self.df.sort_values([
            "query_name", 
            f"{alignment}_from", 
            f"{alignment}_to"
        ])

        overlapping_ratios = []
        accession2architecture = {}
        for row in df.itertuples():
            
            # Gather information
            domain_name = row.pfam_accession
            accession_name = row.query_name.split('|')[1]
            hit_start = getattr(row, f"{alignment}_from")
            hit_end = getattr(row, f"{alignment}_to")

            # Initialize accession architecture
            if accession_name not in accession2architecture:
                accession2architecture[accession_name] = [[domain_name]]
                previous_start = hit_start
                previous_end = hit_end
                continue

            # No overlap or same domain 
            last_domain_name = accession2architecture[accession_name][-1][-1]
            if hit_start > previous_end or domain_name == last_domain_name:
                accession2architecture[accession_name].append([domain_name])
                previous_start = hit_start
                previous_end = hit_end
                continue

            # Overlap
            overlap_start = max(previous_start, hit_start)
            overlap_end = min(previous_end, hit_end)
            overlap_length = overlap_end - overlap_start + 1
            previous_length = previous_end - previous_start + 1
            hit_length = hit_end - hit_start + 1
            overlap_ratio = overlap_length / min(previous_length, hit_length)
            overlapping_ratios.append(overlap_ratio)
            if overlap_ratio > threshold:
                accession2architecture[accession_name][-1].append(domain_name) 
                previous_end = max(previous_end, hit_end)
            else:
                accession2architecture[accession_name].append([domain_name])
                previous_start = hit_start
                previous_end = hit_end

        # Instantiate architectures
        for accession, architecture in accession2architecture.items():
            accession2architecture[accession] = DomainArchitecture(architecture)

        return accession2architecture, np.array(overlapping_ratios)

if __name__ == "__main__":
    d = Domtblout.from_file('/home/asanchez/chonky/POFFT/reports/hmmer/0.domtblout')
    print(d.solve_overlap(alignment='env', threshold=0.5))